# Sample .travis.yml for R projects.
#
# See https://github.com/craigcitro/r-travis
#     https://github.com/eddelbuettel/r-travis/

language: c

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_r highlight
  - if [ "$RCPP" = "release" ]; then ./travis-tool.sh install_r Rcpp; fi
  - if [ "$RCPP" = "constcorrect" ]; then cd ..; git clone https://github.com/romainfrancois/Rcpp.git; R CMD INSTALL Rcpp; cd -; fi
  
script:
  - ./travis-tool.sh run_tests

notifications:
  email:
    on_success: change
    on_failure: change

env:
  - RCPP=release 
  - RCPP=constcorrect 

